framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        message_bus: false
        envelope:
            sender: 'noreply@spacecoder.fun'
        headers:
            From: 'Serge Mezui <noreply@spacecoder.fun>'
            Bcc: 'noreply@spacecoder.fun'
            X-Custom-Header: 'Serge Mezui'
