framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        message_bus: false
        envelope:
            sender: 'serge.mezui@alphoncine.sergemezui.dev'
        headers:
            From: 'Serge Mezui <serge.mezui@alphoncine.sergemezui.dev>'
            Bcc: 'serge.mezui@alphoncine.sergemezui.dev'
            X-Custom-Header: 'Serge Mezui'
